### ISSUE TITLE
Additional argument to pass new elements into S3FS s3_additional_kwargs

### ISSUE THREAD

**Issue by AbominableTurtle** [danielfrg/s3contents#109]
Hi
I have a use case where two separate Jupyter instances under different aws accounts are using the same s3 bucket through s3contents and hybridcontents. When a new directory is created in a bucket in one of these instances via the Jupyter ui, it causes a perms issue where the directory can't be accessed in both instances. In our own use of s3fs I was able to resolve this by providing the follow entry s3_additional_kwargs['ACL'] = 'bucket-owner-full-control' when defining our s3fs.S3FileSystem.

Would it be possible to allow new elements for s3_additional_kwargs to be passed from S3ContentsManager to S3FS when defining my manager classes for HybridContentsManager in the jupyter_config.py?

Looking at S3FileSystem it seems that the ACL kwarg is only used after creating the file system, would it be possible to simply extend S3ContentsManager to achieve this e.g. 

```
class MattsS3ContentsManager(S3ContentsManager):
    def __init__(self, *args, **kwargs):
        super(MattsS3ContentsManager, self).__init__(*args, **kwargs)
        
        self._fs.fs.s3_additional_kwargs["ACL"] = "foo"
```

then use this in the jupyter_config.py?

**Comment by danielfrg** [comment]
That should be an easy fix, are you interested in making a PR?

**Comment by AbominableTurtle** [comment]
Happy to.

**Comment by AbominableTurtle** [comment]
Hi, when should I expect this to be released on pypi?

**Comment by danielfrg** [comment]
Version 0.6.1 is now released on PyPI.
