### ISSUE TITLE
S3 client parameter endpoint_url should not be set when s3 access point is used.

### ISSUE THREAD

**Issue by mengfeng113** [danielfrg/s3contents#113]
In class [S3FS](https://github.com/danielfrg/s3contents/blob/83f764add23223df2622a52db6ad86a94020cbb6/s3contents/s3_fs.py#L33), the [endpoint_url](https://github.com/danielfrg/s3contents/blob/83f764add23223df2622a52db6ad86a94020cbb6/s3contents/s3_fs.py#L74) is always set when creating s3 client. The default value is `s3.amazonaws.com`. However, when caller uses [s3 access point](https://aws.amazon.com/s3/features/access-points/) as notebooks storage (instead of S3 bucket), the bucket is set to a [S3 access point ARN](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-access-points.html). In this scenario, an endpoint_url is not allowed to set in S3 Client - it will result in [validation failure in botocore](https://github.com/boto/botocore/blob/develop/botocore/utils.py#L1537-L1543).

The solution is not passing endpoint_url, or pass None, when bucket is in format of [S3 access point ARN](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-access-points.html).

**Comment by danielfrg** [comment]
Fixed on #114
