### ISSUE TITLE
Folders don't actually exist on file system

### ISSUE THREAD

**Issue by reallyrandom** [danielfrg/s3contents#116]
Anyone use hybridcontents and is able to get their directories to actually be real folders on the notebook server?
for example, the s3 folder will appear in the file browser widget with this code:

```
c.HybridContentsManager.manager_kwargs = {
    # Args for the LargeFileManager mapped to $HOME
    '': {
        'root_dir': os.environ.get("HOME"),
    },
    # Args for S3ContentManager.
    # It is possible to use IAM Role-based access to the S3 bucket from an Amazon ECS instance.
    # To do that just leave access_key_id and secret_access_key set to their default values (None), and ensure that the ECS instance has an IAM role which provides sufficient permissions for the bucket and the operations necessary.
    's3': {
        "access_key_id": None,
        "secret_access_key": None,
        "bucket": os.envrion.get("BUCKET"),
    },
}
```

but, "s3" doesn't actually exist on the file system. This makes us unable to reference any files that live in the s3 folder and makes many other use cases impossible without cloning data and moving it to the home directory or similar.

I tried manually creating the s3 folder but that just creates a duplicated folder.

this is probably just working as intended because I am browsing the bucket from the UI instead of the actual file system.

**Comment by danielfrg** [comment]
s3fs-fuse is the way to go for this type of use cases.
