### ISSUE TITLE
Support empty Token for GCS

### ISSUE THREAD

**Issue by cory-pison** [danielfrg/s3contents#120]
When trying to provide no token for GCS, I get this error:

`
      File "/usr/local/lib/python3.8/dist-packages/s3contents/gcs_fs.py", line 40, in __init__
        token = os.path.expanduser(self.token)
      File "/usr/lib/python3.8/posixpath.py", line 231, in expanduser
        path = os.fspath(path)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
`

For running inside a VM or container on Google cloud, the token does not need to be provided.

Is there a supported way to not use a token?

**Comment by danielfrg** [comment]
There was a bug that expanded that token if its not provided, that has been fixed on 0.7.0 but I cannot test on GCP so not sure its really fixed until some tests this.
