### ISSUE TITLE
S3fs upgrade version

### ISSUE THREAD

**Issue by jacky92** [danielfrg/s3contents#125]
Is it possible to upgrade s3fs version and release again. New version of s3fs use aiobotocore. Thanks

**Comment by danielfrg** [comment]
Fixed on https://github.com/danielfrg/s3contents/commit/afdeb25a2b05cbf381bab17bd5ab4ef03f22e873.

I will make a release today

**Comment by jacky92** [comment]
Thanks danielfrg! I will integrate it next week
