### ISSUE TITLE
Last Modified Date

### ISSUE THREAD

**Issue by tomz** [danielfrg/s3contents#13]
Hi,
Any reason that DUMMY_CREATED_DATE = datetime.fromtimestamp(0) is used in Last Modified? As the result Last Modified were shown as "49 Years ago"

Thanks,
Tom

**Comment by danielfrg** [comment]
Yeah, this is a bug.

**Comment by lsglick** [comment]
Any chance this will get resolved soon? Thanks!

**Comment by danielfrg** [comment]
This has been fixed and is available on pypi as version `0.1.4`.

**Comment by etheleon** [comment]
FYI. 

Dates for files are displayed correctly but the folders still reflect 49 years. Don't think there's a way around this right?
