### ISSUE TITLE
delete markers cause ghost folders when listing versioned bucket

### ISSUE THREAD

**Issue by Zhell1** [danielfrg/s3contents#130]
## Issue description

s3contents doesn't seem to handle ListObjectsV2 action properly with versioned buckets as it displays all prefixes without making sure if they are delete marker or actual "folders".

## Steps to reproduce

- activate versioning on a bucket
- create a folder
- delete (or rename) the folder
- refresh jupyterlab
- the supposed-to-be-deleted folder will still show up in the filesystem, but will be unopenable & will have a `Last Modified` date of `52 years ago`. Any action on the folder (like opening) will return a `Folder not found` as expected by s3.

## Fix hints

(currently working on this, hope to have a PR coming in a few days)

Note: in Minio the versioning is unavailable in a single-disk setup, and requires to deploy in Distributed Mode to use it.

The ListBucketResult returning a KeyCount of 0 might be enough to indicate that the folder is a delete marker and hide it in the filesystem?

```html
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
   <Name>mybucket</Name>
   <Prefix>myprefix/test/</Prefix>
   <KeyCount>0</KeyCount>
   <MaxKeys>1</MaxKeys>
   <Delimiter>/</Delimiter>
   <IsTruncated>false</IsTruncated>
   <EncodingType>url</EncodingType>
</ListBucketResult>
```

**Comment by danielfrg** [comment]
Fixed by https://github.com/danielfrg/s3contents/pull/134
