### ISSUE TITLE
Error when using GCS content manager in s3contents==0.9.0

### ISSUE THREAD

**Issue by yucensun** [danielfrg/s3contents#152]
Hi,

I'm getting the following error when trying to use the gcs content manager:

> `File "***/s3contents/genericmanager.py", line 146, in get
>     return func(path=path, content=content, format=format)
> 
>   File "***/s3contents/genericmanager.py", line 155, in _get_directory
>     return self._directory_model_from_path(path, content=content)
> 
>   File "***/s3contents/genericmanager.py", line 222, in _directory_model_from_path
>     self.fs.fs.loop, self.fs.fs._lsdir, prefixed_path
> 
> AttributeError: 'GCSFileSystem' object has no attribute '_lsdir'`

Versions:
s3contents==0.9.0
fssepc==2022/8/2
gcsfs==2022/8/2
s3fs==2022/8/2

**Comment by lucienfregosibodyguard** [comment]
Any workaround @danielfrg ?

**Comment by yucensun** [comment]
@lucienfregosibodyguard this should be fixed by the above pr

**Comment by danielfrg** [comment]
Fixed on #170
