### ISSUE TITLE
How could I get the current path inside the S3 bucket from within the open notebook?

### ISSUE THREAD

**Issue by djuarezg** [danielfrg/s3contents#171]
So, I have a notebook open in Jupyter which is stored in S3. This one is opened thanks to s3contents.

On the open tab I see that the path correctly reports the dir path on the file browser, but the notebook is unaware of it.

How can I retrieve the "virtual" path?

![image](https://github.com/danielfrg/s3contents/assets/34030545/08a946aa-173b-4337-a47d-a89fe8e299b7)
![image](https://github.com/danielfrg/s3contents/assets/34030545/104c69b0-ad60-411e-942f-83b44c42b9d3)

**Comment by djuarezg** [comment]
```
#! pip install ipynbname

import ipynbname
nb_fname = ipynbname.name()
nb_path = ipynbname.path()
```

**Comment by GomesNayagam** [comment]
this is not working when i use s3contentmanager
