### ISSUE TITLE
Uploaded files end up being base64-encoded  

### ISSUE THREAD

**Issue by Corni** [danielfrg/s3contents#22]
Hi,

any files I upload besides jupyter notebooks end up being base64-encoded in the web viewer when I open them. I expect to be able to upload  a txt or ini file and then open it without it being base64-encoded.

This happens with s3contents 0.1.4 on
jupyter==1.0.0
jupyter-client==5.0.0
jupyter-console==5.1.0
jupyter-core==4.3.0
ipykernel==4.5.2
ipython==5.3.0
ipython-genutils==0.2.0
ipywidgets==6.0.0

**Comment by SurajZinjad** [comment]
Facing same issue, any update ?

**Comment by rhlnair87** [comment]
I had same issue, it looks like just changing the code a bit in s3fs.py fixes the issue. Had to decode the file before its uploaded to S3.

    def write(self, path, content):
        import base64
        content1 = base64.b64decode(content)
        key = self.as_key(path)
        self.client.put_object(Bucket=self.bucket_name, Key=key, Body=content1)

Should be a bug in previous version that come with pip.

-Rahul N.

**Comment by SurajZinjad** [comment]
Hi Rahul,

Making above changes solve encode issue, but now when I create notebook it give me error.

Thanks.

**Comment by rhlnair87** [comment]
Ahh ok, we can create a separate function writenotebook() to deal the writes separately for notebook and used it for _save_notebook()

Changes for s3fs.py:


    def write(self, path, content):
        import base64
        content1 = base64.b64decode(content)
        key = self.as_key(path)
        self.client.put_object(Bucket=self.bucket_name, Key=key, Body=content1)

    def writenotebook(self, path, content):
        key = self.as_key(path)
        self.client.put_object(Bucket=self.bucket_name, Key=key, Body=content)


Changes for s3manager.py:


    def _save_notebook(self, model, path):
        nb_contents = from_dict(model['content'])
        self.check_and_sign(nb_contents, path)
        file_contents = json.dumps(model["content"])
        self.s3fs.writenotebook(path, file_contents)
        self.validate_notebook_model(model)
        return model.get("message")


-Rahul N
