### ISSUE TITLE
Consider using the s3fs package

### ISSUE THREAD

**Issue by mrocklin** [danielfrg/s3contents#23]
This might be able to remove some code in this repository.  If it doesn't do something that it should I'd love to hear about it.  http://s3fs.readthedocs.io/en/latest/

**Comment by danielfrg** [comment]
I remember trying it when I wrote this and I know I had a blocker that might have to do with the `prefix` but I don't remember exactly. I would like to use all this external libraries for sure.

**Comment by danielfrg** [comment]
I think there is also some functions that don't exist, like creating a dir, since technically there is no dirs in S3 so I had to create some stub functions for that.

**Comment by danielfrg** [comment]
I refactored to use it on https://github.com/danielfrg/s3contents/pull/24.

There is some weird decisions on s3fs about how to handle buckets and directories so i had to go around them but in general i was able to remove a lot of code from here.

**Comment by mrocklin** [comment]
Awesome.  Glad to hear it.
