### ISSUE TITLE
Bad config encountered during initialization:

### ISSUE THREAD

**Issue by anasos** [danielfrg/s3contents#34]
Hi
I'm using jupyterhub i try to redirect my directory to S3 bucket.
I get this error when run jupyterhub : 
 
```
[C 2018-03-22 11:17:15.116 SingleUserNotebookApp application:90] Bad config encountered during initialization:
[C 2018-03-22 11:17:15.116 SingleUserNotebookApp application:91] The 'contents_manager_class' trait of <jupyterhub.singleuser.SingleUserNotebookApp object at 0x7f1240666198> instance must be a type, but 'S3ContentsManager' could not be imported
```
my jupyter_notebook_config.py content : 

```
import os
from jupyterhub.spawner import LocalProcessSpawner
from s3contents import S3ContentsManager

c = get_config()

c.NotebookApp.contents_manager_class = 'S3ContentsManager'
c.S3ContentsManager.access_key_id = "A**********************************"
c.S3ContentsManager.secret_access_key = "e*******************************************"
c.S3ContentsManager.bucket_name = 'bucket-name'
c.S3ContentsManager.prefix = 'notebooks'


```
Thanks for the help.

**Comment by danielfrg** [comment]
You are passing a string `'S3ContentsManager'` but it should the`S3ContentsManager` class. Remove the quotes.

Pls reopen if that doesnt firx it.

**Comment by anasos** [comment]
@danielfrg thanks for the reply it works !!!

I have another question : is there a way to make the c.S3ContentsManager.prefix dynamic to look like : 

`c.S3ContentsManager.prefix = '/{username}/notebook/'
`
Thanks again.

Should i put this question in a new issue ??

**Comment by danielfrg** [comment]
Not really but you can just do it in the config file like:

```python
username = "daniel"
c.S3ContentsManager.prefix = '/{username}/notebook/'.format(username=username)
```

**Comment by anasos** [comment]
Thanks again @danielfrg but this is not what i really want.

I'm using the jupyter hub installed in an EC2 instance , so for example at first when the storage was in the EC2 instance i managed to add this code that i found in another issue:

```
class MySpawner(LocalProcessSpawner):
    def _notebook_dir_default(self):
        user_directory = self.user.name.split("@")[0]
        return '/home/' + self.user.name + '/notebook/' + user_directory

c.JupyterHub.spawner_class = MySpawner
```

This code allowed me to redirect every user in his private repository.

So can this solution be used for my case with the S3. With the override a specific function.

**Comment by danielfrg** [comment]
Yes, so that function we don't have but I bet you can write something very similar in the `jupyter_notebook_config.py` by reading the username thats running the notebook (`getpass.getuser()`) and calling on `c.S3ContentsManager.prefix = func()`.

**Comment by anasos** [comment]
Thanks again @danielfrg for your help. I tried the s3fs-fuse. It gives me the result i want.

**Comment by diogozedan** [comment]
@anasos can you explain how you did it?
