### ISSUE TITLE
Support IAM role-based access (no access_key_id or secret_access_key)

### ISSUE THREAD

**Issue by kpfleming** [danielfrg/s3contents#4]
When running on an EC2 instance, it's possible to use IAM roles to grant the instance itself access to an S3 bucket, so that no access keys are required (and thus they can't be accidentally compromised). In order for this to work, when requests are made via boto, the caller must not specify the access_key_id or secret_access_key parameters at all (they are left out of the argument list).

I hacked the copy of s3contents on my system to remove these arguments in s3manager.py and s3fs.py to see if I could make it work, and it does work, but I'm not sure how this sort of thing should be exposed to the actual configuration of s3contents. If you're interested in addressing this, I'm happy to help come up with a suitable solution!

**Comment by danielfrg** [comment]
Yes, we should add this. Can you check if it works if you pass `None` as `access_key_id` and `secret_access_key`.

**Comment by kpfleming** [comment]
Unfortunately it doesn't work:
```
[C 19:09:48.862 NotebookApp] Bad config encountered during initialization:
[C 19:09:48.862 NotebookApp] The 'secret_access_key' trait of a S3ContentsManager instance must be a unicode string, but a value of None <type 'NoneType'> was specified.
```

**Comment by kpfleming** [comment]
However, with some small changes to s3manager.py and s3fs.py it can be made to work. I'll open a PR soon.
