### ISSUE TITLE
It's not working with S3 Server Scality

### ISSUE THREAD

**Issue by mlevos** [danielfrg/s3contents#43]
I try s3contents with a s3 scality server but each time i try to connect my notebook to the s3 server, it's rise a FileNotFound exception.

**Comment by danielfrg** [comment]
I have not tested it but I would guess its a configuration option. Probably depending on the AWS Signature Version (3 or 4) or something like that.

**Comment by danielfrg** [comment]
Closing for now  since its difficult for us to test this but its probably the case was fixed at one point with the new versions. if people still have the problem pls open a new issue
