### ISSUE TITLE
Missing release tag, and no changelog

### ISSUE THREAD

**Issue by adamchainz** [danielfrg/s3contents#54]
I see there's a version 0.1.12 on PyPI, but it seems the release tag wasn't pushed to GitHub, as the release process in `RELEASE.md` would imply. Was it just missed?

Also ideally there would be a changelog describing the changes in simple user-facing language. Reading git logs isn't always easy, especially when upgrading tens of packages at once :)

**Comment by danielfrg** [comment]
Yes, I missed one tag its fixed now.
Agree that changelog is nice i need to be better at those things :) I added one on https://github.com/danielfrg/s3contents/pull/60
