### ISSUE TITLE
%2F prefix in file names

### ISSUE THREAD

**Issue by amangarg96** [danielfrg/s3contents#57]
I'm using s3contents with JupyterLab on a Ceph based Object store (with s3).

I'm using signature v2 (signature_version='s3').

On JupyterLab, every filename is getting a prefix '%2f', which can be seen in the screenshot below

![image](https://user-images.githubusercontent.com/16137472/51374869-4f07d300-1b2a-11e9-80e9-101c7ac89968.png)

Also, I ran the following code to list the contents of the bucket

```
from s3contents.s3_fs import S3FS
import logging
s3fs_obj = S3FS(logging,
                access_key_id=<access_key_id>,
                secret_access_key=<secret_access_key>,
                endpoint_url=<endpoint_url>,
                signature_version='s3',
                bucket='amantestbucket',
                prefix='')
print(s3fs_obj.ls('amantestbucket/notebook'))
```

Which gives the following output
`['notebook%2F.s3keep', 'notebook%2FUntitled.ipynb', 'notebook%2FUntitled1.ipynb', 'notebook%2Ftouch-text.txt', 'notebook%2Fwrite_file.txt', 'notebook%2Fwrite_notebook', 'notebook/folder_mkdir', 'notebook/notebook']
`

So all the '/' before the filenames seem to be encoded as '%2F'.

It's causing issues, when I'm trying to open non-.ipynb files. (Screenshot below)
![image](https://user-images.githubusercontent.com/16137472/51375945-246b4980-1b2d-11e9-9702-487ebf762ed4.png)

Even with .ipynb files, renaming files causes an issue, because of the '%2F'. (Screenshot below)
![image](https://user-images.githubusercontent.com/16137472/51376110-8cba2b00-1b2d-11e9-8712-c26c25cb0bea.png)
Error in the Notebook server log:
`No such entity: [%2FUntitled1.ipynb]`

I'm able to create new Notebooks, but not able to open the newly created notebooks (Screenshot below)
![image](https://user-images.githubusercontent.com/16137472/51376241-defb4c00-1b2d-11e9-9da1-a5594c20b100.png)

All these issues seem to be due to the invalid parsing of the paths, because of the '%2F' encoding.
What should be way to resolve this?

**Comment by danielfrg** [comment]
This is probably not an issue in newer versions pls open a new issue if this is still the case.
