### ISSUE TITLE
Provide ServerSideEncryption while setting up s3contents

### ISSUE THREAD

**Issue by pankajtaneja** [danielfrg/s3contents#58]
I would like to setup ServerSideEncryption while using s3contents for jupyter notebooks. The idea is to provide additional arguments like extra_args={'ServerSideEncryption': "AES256"}

import boto3
client = boto3.client('s3')
transfer = boto3.s3.transfer.S3Transfer(client=client)
transfer.upload_file('testfile', bucket, prefix+'testfile', extra_args={'ServerSideEncryption': "AES256"})

Is there a variable in S3ContentsManager that can be used ?

**Comment by danielfrg** [comment]
There is already an option to configure the ServerSideEncryption like:

```
c.S3ContentsManager.sse = "AES256"
```

I'll add it to the README since its missing.
