### ISSUE TITLE
User Folder in S3 Directory

### ISSUE THREAD

**Issue by morganhferry** [danielfrg/s3contents#69]
We are using S3Contents in conjunction with JupyterHub. We would like to be able to indicate in the prefix a username. Some sort of flag that picks up the user and creates their directory in S3 within their folder name. Is this already possible? IE in the /etc/jupyter/jupyter_notebook_config.py file:

c.S3ContentsManager.prefix = "$USER/jupyter_notebooks"

**Comment by danielfrg** [comment]
Yes, you can do it just in the `jupyter_notebook_config.py`:

```python
import getpass
username = getpass.getuser()
...
c.S3ContentsManager.prefix = os.path.join(username, "jupyter_notebooks")
```

**Comment by morganhferry** [comment]
Ah, perfect. Thank you!
